-- Create READLIST tables for PostgreSQL
-- Converted from SQLite readlists migration

CREATE TABLE READLIST (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    BOOK_COUNT INTEGER NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE READLIST_BOOK (
    READLIST_ID VARCHAR(36) NOT NULL,
    BOOK_ID VARCHAR(36) NOT NULL,
    NUMBER INTEGER NOT NULL,
    PRIMARY KEY (READLIST_ID, BOOK_ID),
    FOREIGN KEY (READLIST_ID) REFERENCES READLIST (ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID) ON DELETE CASCADE
);

-- Add column to library table
ALTER TABLE LIBRARY ADD COLUMN IMPORT_COMICINFO_READLIST BOOLEAN NOT NULL DEFAULT TRUE;

-- Create indices for performance
CREATE INDEX idx_readlist_book_readlist_id ON READLIST_BOOK(READLIST_ID);
CREATE INDEX idx_readlist_book_book_id ON READLIST_BOOK(BOOK_ID);