-- Initial migration for PostgreSQL
-- Converted from SQLite schema

-- LIBRARY table
CREATE TABLE LIBRARY (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    ROOT VARCHAR NOT NULL UNIQUE,
    IMPORT_COMIC_INFO_BOOK BOOLEAN NOT NULL DEFAULT TRUE,
    IMPORT_COMIC_INFO_SERIES BOOLEAN NOT NULL DEFAULT TRUE,
    IMPORT_COMIC_INFO_COLLECTION BOOLEAN NOT NULL DEFAULT TRUE,
    IMPORT_COMIC_INFO_READ_LIST BOOLEAN NOT NULL DEFAULT TRUE,
    IMPORT_EPUB_BOOK BOOLEAN NOT NULL DEFAULT TRUE,
    IMPORT_EPUB_SERIES BOOLEAN NOT NULL DEFAULT TRUE,
    IMPORT_LOCAL_ARTWORK BOOLEAN NOT NULL DEFAULT TRUE,
    IMPORT_BARCODES_ISBN BOOLEAN NOT NULL DEFAULT TRUE,
    SCAN_FORCE_MODIFIED_TIME BOOLEAN NOT NULL DEFAULT FALSE,
    SCAN_DEEP BOOLEAN NOT NULL DEFAULT FALSE,
    REPAIR_EXTENSIONS BOOLEAN NOT NULL DEFAULT FALSE,
    CONVERT_TO_CBZ BOOLEAN NOT NULL DEFAULT FALSE,
    EMPTY_TRASH_AFTER_SCAN BOOLEAN NOT NULL DEFAULT FALSE,
    SERIES_COVER SMALLINT NOT NULL DEFAULT 0,
    HASH_FILES BOOLEAN NOT NULL DEFAULT TRUE,
    HASH_PAGES BOOLEAN NOT NULL DEFAULT FALSE,
    ANALYZE_DIMENSIONS BOOLEAN NOT NULL DEFAULT TRUE,
    UNAVAILABLE_DATE TIMESTAMP
);

-- USER table
CREATE TABLE "USER" (
    ID VARCHAR(36) PRIMARY KEY,
    EMAIL VARCHAR NOT NULL UNIQUE,
    PASSWORD VARCHAR NOT NULL,
    ROLE_ADMIN BOOLEAN NOT NULL DEFAULT FALSE,
    ROLE_FILE_DOWNLOAD BOOLEAN NOT NULL DEFAULT FALSE,
    ROLE_PAGE_STREAMING BOOLEAN NOT NULL DEFAULT FALSE,
    SHARED_LIBRARIES_IDS VARCHAR,
    SHARED_ALL_LIBRARIES BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW()
);

-- USER_LIBRARY_SHARING table
CREATE TABLE USER_LIBRARY_SHARING (
    USER_ID VARCHAR(36) NOT NULL,
    LIBRARY_ID VARCHAR(36) NOT NULL,
    PRIMARY KEY (USER_ID, LIBRARY_ID),
    FOREIGN KEY (USER_ID) REFERENCES "USER"(ID) ON DELETE CASCADE,
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY(ID) ON DELETE CASCADE
);

-- SERIES table
CREATE TABLE SERIES (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    URL VARCHAR NOT NULL UNIQUE,
    FILE_LAST_MODIFIED TIMESTAMP NOT NULL,
    LIBRARY_ID VARCHAR(36) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY(ID) ON DELETE CASCADE
);

-- SERIES_METADATA table
CREATE TABLE SERIES_METADATA (
    SERIES_ID VARCHAR(36) PRIMARY KEY,
    STATUS VARCHAR NOT NULL DEFAULT 'ONGOING',
    TITLE VARCHAR NOT NULL,
    TITLE_SORT VARCHAR NOT NULL,
    SUMMARY TEXT,
    READING_DIRECTION VARCHAR,
    PUBLISHER VARCHAR,
    AGE_RATING SMALLINT,
    LANGUAGE VARCHAR,
    GENRES VARCHAR,
    TAGS VARCHAR,
    TOTAL_BOOK_COUNT INTEGER,
    STATUS_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    TITLE_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    TITLE_SORT_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    SUMMARY_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    READING_DIRECTION_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    PUBLISHER_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    AGE_RATING_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    LANGUAGE_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    GENRES_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    TAGS_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    TOTAL_BOOK_COUNT_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES(ID) ON DELETE CASCADE
);

-- BOOK table
CREATE TABLE BOOK (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    URL VARCHAR NOT NULL UNIQUE,
    FILE_LAST_MODIFIED TIMESTAMP NOT NULL,
    FILE_SIZE BIGINT NOT NULL DEFAULT 0,
    SERIES_ID VARCHAR(36) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES(ID) ON DELETE CASCADE
);

-- MEDIA table
CREATE TABLE MEDIA (
    ID VARCHAR(36) PRIMARY KEY,
    BOOK_ID VARCHAR(36) NOT NULL UNIQUE,
    STATUS VARCHAR NOT NULL DEFAULT 'UNKNOWN',
    MEDIA_TYPE VARCHAR,
    PAGES_COUNT INTEGER NOT NULL DEFAULT 0,
    COMMENT VARCHAR,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE
);

-- MEDIA_PAGE table
CREATE TABLE MEDIA_PAGE (
    BOOK_ID VARCHAR(36) NOT NULL,
    NUMBER INTEGER NOT NULL,
    FILE_NAME VARCHAR NOT NULL,
    MEDIA_TYPE VARCHAR,
    DIMENSION_WIDTH INTEGER,
    DIMENSION_HEIGHT INTEGER,
    PRIMARY KEY (BOOK_ID, NUMBER),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE
);

-- MEDIA_FILE table
CREATE TABLE MEDIA_FILE (
    ID VARCHAR(36) PRIMARY KEY,
    BOOK_ID VARCHAR(36) NOT NULL,
    FILE_NAME VARCHAR NOT NULL,
    MEDIA_TYPE VARCHAR,
    SUB_TYPE VARCHAR,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE
);

-- BOOK_METADATA table
CREATE TABLE BOOK_METADATA (
    BOOK_ID VARCHAR(36) PRIMARY KEY,
    TITLE VARCHAR NOT NULL,
    TITLE_SORT VARCHAR NOT NULL,
    SUMMARY TEXT,
    NUMBER VARCHAR NOT NULL,
    NUMBER_SORT REAL NOT NULL,
    RELEASE_DATE DATE,
    AUTHORS VARCHAR,
    ISBN VARCHAR,
    TAGS VARCHAR,
    TITLE_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    TITLE_SORT_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    SUMMARY_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    NUMBER_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    NUMBER_SORT_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    RELEASE_DATE_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    AUTHORS_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    ISBN_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    TAGS_LOCK BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE
);

-- BOOK_METADATA_AUTHOR table
CREATE TABLE BOOK_METADATA_AUTHOR (
    BOOK_ID VARCHAR(36) NOT NULL,
    NAME VARCHAR NOT NULL,
    ROLE VARCHAR NOT NULL,
    PRIMARY KEY (BOOK_ID, NAME, ROLE),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE
);

-- READ_PROGRESS table
CREATE TABLE READ_PROGRESS (
    BOOK_ID VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    PAGE INTEGER NOT NULL,
    COMPLETED BOOLEAN NOT NULL DEFAULT FALSE,
    READ_DATE TIMESTAMP,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (BOOK_ID, USER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES "USER"(ID) ON DELETE CASCADE
);

-- COLLECTION table
CREATE TABLE COLLECTION (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    ORDERED BOOLEAN NOT NULL DEFAULT TRUE,
    SERIES_IDS VARCHAR,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW()
);

-- COLLECTION_SERIES table
CREATE TABLE COLLECTION_SERIES (
    COLLECTION_ID VARCHAR(36) NOT NULL,
    SERIES_ID VARCHAR(36) NOT NULL,
    NUMBER INTEGER NOT NULL,
    PRIMARY KEY (COLLECTION_ID, SERIES_ID),
    FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION(ID) ON DELETE CASCADE,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES(ID) ON DELETE CASCADE
);

-- Create indices for performance
CREATE INDEX idx_series_library_id ON SERIES(LIBRARY_ID);
CREATE INDEX idx_book_series_id ON BOOK(SERIES_ID);
CREATE INDEX idx_media_book_id ON MEDIA(BOOK_ID);
CREATE INDEX idx_media_page_book_id ON MEDIA_PAGE(BOOK_ID);
CREATE INDEX idx_media_file_book_id ON MEDIA_FILE(BOOK_ID);
CREATE INDEX idx_book_metadata_book_id ON BOOK_METADATA(BOOK_ID);
CREATE INDEX idx_book_metadata_author_book_id ON BOOK_METADATA_AUTHOR(BOOK_ID);
CREATE INDEX idx_read_progress_book_id ON READ_PROGRESS(BOOK_ID);
CREATE INDEX idx_read_progress_user_id ON READ_PROGRESS(USER_ID);
CREATE INDEX idx_collection_series_collection_id ON COLLECTION_SERIES(COLLECTION_ID);
CREATE INDEX idx_collection_series_series_id ON COLLECTION_SERIES(SERIES_ID);
CREATE INDEX idx_user_library_sharing_user_id ON USER_LIBRARY_SHARING(USER_ID);
CREATE INDEX idx_user_library_sharing_library_id ON USER_LIBRARY_SHARING(LIBRARY_ID);