-- API Key support for PostgreSQL
-- Converted from SQLite API key migration

-- Create USER_API_KEY table
CREATE TABLE USER_API_KEY (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    COMMENT VARCHAR,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (USER_ID) REFERENCES "USER"(ID) ON DELETE CASCADE
);

-- Add columns to AUTHENTICATION_ACTIVITY table
ALTER TABLE AUTHENTICATION_ACTIVITY ADD COLUMN API_KEY_ID VARCHAR(36);
ALTER TABLE AUTHENTICATION_ACTIVITY ADD COLUMN API_KEY_COMMENT VARCHAR;

-- Add foreign key constraint for API_KEY_ID
ALTER TABLE AUTHENTICATION_ACTIVITY 
    ADD CONSTRAINT fk_authentication_activity_api_key 
    FOREIGN KEY (API_KEY_ID) REFERENCES USER_API_KEY(ID) ON DELETE SET NULL;

-- Create index for performance
CREATE INDEX idx_user_api_key_user_id ON USER_API_KEY(USER_ID);
CREATE INDEX idx_authentication_activity_api_key_id ON AUTHENTICATION_ACTIVITY(API_KEY_ID);